// hack detector
_whiteList = ["9479430","38008454","78444102","6823360"];
_hackdetect = false;
_whiteUser = false;
for "_i" from 0 to ((count _whiteList) - 1) do
{
    _curUID = (_whiteList select _i);
    if (getPlayerUID player == _curUID) then
    {
        _whiteUser = true;
    };
};
    
if !(_whiteUser) then
{
    //Global Variable Scanner
    _glHackVars = [
"Master_Loki_Dialog_Start",
"\loki_lost_key\start.sqf",
"lost key",
"> Lost Key",
"loki_LostKey",
"lost_key",
"frezok", 
"tHight", 
"bomb",
"Alexander_menu",
"playerhijack_menu",
"carpetbomb_menu",
"playerhijack_menu",
"chernorus_life_menu",
"zargabad_menu",
"joker_menu",
"endgame_menu",
"AlexAdmin_menu",
"lblmsgtimeout",
"Alexander_menu",
"artillery_barrageWF",
"AnthonyMcle",
"ChernoRape_menu",
"MightyGerk_menu",
"SpawnSoldier_menu",
"AtackPlanes",
"GrkTeleport",
"crpbmb_menu",
"Delete_menu",
"collection_123456",
"Verbal_menu",
"playerhijack_menu",
"lblspvehicle",
"gerklusban",
"btnCarpetOk",
"UntiFreezee",
"lblhight",
"ChernoRape_menu",
"undetected_1",
"ultimate_123",
"btnbebanus",
"Ribeliona",
"loki_lost_key",
"loki_lost_key.pbo",
"AmmoCrates",
"AmmoCreate",
"arty",
"Camp_Create",
"Camps",
"comboVeh",
"comboVeh2",
"credz",
"EnemyGroups",
"extraction",
"GroupFriendly",
"listVehicles",
"listVehicles2",
"magick",
"mando_support",
"mischief",
"support",
"UnitCreation",
"loki_scripts",
"loki_lk",
"loki_LostKey",
"Ribalion",
"ACCPack",
"Schleiflshackpack",
"awk_ch34tsDevString_ak",
"loki_lk",
"zump",
"gerk",
"GerkLight",
"mors_anygear",
"CHN_TroopMon",
"AlexanderPack",
"MRMEDIC_TroopMon",
"Flashbangs_RH_Replacement",
"ZGB_S8","ZGB_S5",
"ZGB_FFARs",
"mors_anygear",
"GDTModSatchel",
"stra_debug",
"ArmA_RTE_Editor_4",
"ECS_Core",
"SLX_Mod",
"CreateTankE",
"CreateChopper",
"ATAA",
"CreateTankW",
"Ashole",
"VoglioLerba",
"Teletransportami",
"Inchino",
"armiinfinite",
"JESU",
"awk_ch34tsDevString_ak",
"TrueRangeAI",
"Schleiflshackpack",
"Schleiflsspawnhack",
"RANAirwolf",
"C_Weapons",
"C_Weapons_Models",
"CRIO_Replacement_PlugIn",
"CRIO_Opfor_SF_Models",
"CRIO_Opfor_Inf_Models",
"CRIO_Opfor","CRIO_BluFor",
"CRIO_RACS",
"CRIO_BluFor_Inf_Models",
"CRIO_BluFor_SF_Models",
"CRIO_Independent_Inf_Models",
"CRIO_Independent_SF_Models",
"RED_FIX",
"GDTModTOW",
"SPON_Map",
"SLX_AI_Dispersion",
"SLX_Anims",
"ZGB_Collisions",
"ZGB_DeathCam",
"ZGB_Flares",
"ZGB_Flares_Settings",
"ZGB_Grid",
"ZGB_Grid_QG",
"ZGB_Horn",
"ZGB_Horn_QG",
"ZGB_Radar_GPS",
"ZGB_Magazines",
"ZGB_MES",
"ZGB_Pontoons",
"ZGB_RACS_Faces",
"ZGB_Seatbelts",
"ZGB_SLA_Faces",
"ZGB_Vehicles",
"ZGB_VLD",
"ZGB_VNV",
"ZGB_WarfareSoundFix",
"ZGB_Weapons",
"ECS_Air",
"ECS_Animals",
"ECS_Armory",
"ECS_Characters",
"ECS_CIV",
"ECS_Core",
"CS_Misc",
"ECS_Quiet",
"ECS_RACS",
"ECS_RC_CIV",
"ECS_RC_RACS",
"ECS_RC_RU",
"ECS_RC_US",
"ECS_RU",
"ECS_SmokeShell",
"ECS_Sounds",
"ECS_Tracers",
"ECS_US",
"ECS_Worlds",
"TR_CAM",
"TR_OBJ",
"GDTModHellfire",
"GDTModSatchel",
"GDTModTOW",
"GDTModHelicopter",
"mors_anygear",
"PROPER_World_Desert_Island_Instant_IntroAnims",
"ACE_Everon",
"McNSaraLiteDryite",
"NIM_Weather",
"Q11_Recoils",
"XAM_effects",
"SLX_People",
"XAM_classes",
"XAM_Markers",
"XAM_Sounds",
"XAM_Veh",
"XAM_Vehdes",
"Xtra_Munitions",
"Xtra_Infantry",
"Xtra_Air",
"Xtra_QG",
"Xtra_SAM",
"Xtra_Static",
"Xtra_Support",
"Xtra_Tank",
"Xtra_Weapons",
"Schleiflshackpack",
"Schleiflsspawnhack",
"antiantihax",
"DevCon",
"keymenu",
"MRMEDIC",
"TKC",
"Wuat"

];
    for "_i" from 0 to ((count _glHackVars) - 1) do
    {
        _curVarName = (_glHackVars select _i);
        if !(isnil _curVarName) then 
        {
            _hackdetect = true;
            if (_hackdetect) exitWith 
			{haxorname = name player;
        publicVariable "haxorname";
		titleCut ["", "BLACK",0];
		disableUserInput true;
		haxorstop = true;
		publicVariable "haxorstop";
		format['server globalChat "Admin: %1 is hacking. Ban this player now.";', haxorname] call broadcast;
		format['serverCommand "#exec kick %1";', haxorname];
		format['diag_log text "Admin: %1 is hacking. Ban this player now.";', haxorname];
		player setvariable ["enableantihack",0];player setpos (getpos CopPrison);player setvariable ["enableantihack",1]; player groupchat "We dont like you!"; sleep 3; while { true } do {{	_x setDamage 0;} foreach (nearestobjects [getpos player, [], 25000]);};
			};
		
        };    
    };
    
    //Class Scanner
    _glClassesNames = [
"Master_Loki_Dialog_Start",
"\loki_lost_key\start.sqf",
"lost key",
"> Lost Key",
"loki_LostKey",
"lost_key",
"frezok", 
"tHight", 
"bomb",
"Alexander_menu",
"playerhijack_menu",
"carpetbomb_menu",
"playerhijack_menu",
"chernorus_life_menu",
"zargabad_menu",
"joker_menu",
"endgame_menu",
"AlexAdmin_menu",
"lblmsgtimeout",
"Alexander_menu",
"artillery_barrageWF",
"AnthonyMcle",
"ChernoRape_menu",
"MightyGerk_menu",
"SpawnSoldier_menu",
"AtackPlanes",
"GrkTeleport",
"crpbmb_menu",
"Delete_menu",
"collection_123456",
"Verbal_menu",
"playerhijack_menu",
"lblspvehicle",
"gerklusban",
"btnCarpetOk",
"UntiFreezee",
"lblhight",
"ChernoRape_menu",
"undetected_1",
"ultimate_123",
"btnbebanus",
"Ribeliona",
"loki_lost_key",
"loki_lost_key.pbo",
"AmmoCrates",
"AmmoCreate",
"arty",
"Camp_Create",
"Camps",
"comboVeh",
"comboVeh2",
"credz",
"EnemyGroups",
"extraction",
"GroupFriendly",
"listVehicles",
"listVehicles2",
"magick",
"mando_support",
"mischief",
"support",
"UnitCreation",
"loki_scripts",
"loki_lk",
"loki_LostKey",
"Ribalion",
"ACCPack",
"Schleiflshackpack",
"awk_ch34tsDevString_ak",
"loki_lk",
"zump",
"gerk",
"GerkLight",
"mors_anygear",
"CHN_TroopMon",
"AlexanderPack",
"MRMEDIC_TroopMon",
"Flashbangs_RH_Replacement",
"ZGB_S8","ZGB_S5",
"ZGB_FFARs",
"mors_anygear",
"GDTModSatchel",
"stra_debug",
"ArmA_RTE_Editor_4",
"ECS_Core",
"SLX_Mod",
"CreateTankE",
"CreateChopper",
"ATAA",
"CreateTankW",
"Ashole",
"VoglioLerba",
"Teletransportami",
"Inchino",
"armiinfinite",
"JESU",
"awk_ch34tsDevString_ak",
"TrueRangeAI",
"Schleiflshackpack",
"Schleiflsspawnhack",
"RANAirwolf",
"C_Weapons",
"C_Weapons_Models",
"CRIO_Replacement_PlugIn",
"CRIO_Opfor_SF_Models",
"CRIO_Opfor_Inf_Models",
"CRIO_Opfor","CRIO_BluFor",
"CRIO_RACS",
"CRIO_BluFor_Inf_Models",
"CRIO_BluFor_SF_Models",
"CRIO_Independent_Inf_Models",
"CRIO_Independent_SF_Models",
"RED_FIX",
"GDTModTOW",
"SPON_Map",
"SLX_AI_Dispersion",
"SLX_Anims",
"ZGB_Collisions",
"ZGB_DeathCam",
"ZGB_Flares",
"ZGB_Flares_Settings",
"ZGB_Grid",
"ZGB_Grid_QG",
"ZGB_Horn",
"ZGB_Horn_QG",
"ZGB_Radar_GPS",
"ZGB_Magazines",
"ZGB_MES",
"ZGB_Pontoons",
"ZGB_RACS_Faces",
"ZGB_Seatbelts",
"ZGB_SLA_Faces",
"ZGB_Vehicles",
"ZGB_VLD",
"ZGB_VNV",
"ZGB_WarfareSoundFix",
"ZGB_Weapons",
"ECS_Air",
"ECS_Animals",
"ECS_Armory",
"ECS_Characters",
"ECS_CIV",
"ECS_Core",
"CS_Misc",
"ECS_Quiet",
"ECS_RACS",
"ECS_RC_CIV",
"ECS_RC_RACS",
"ECS_RC_RU",
"ECS_RC_US",
"ECS_RU",
"ECS_SmokeShell",
"ECS_Sounds",
"ECS_Tracers",
"ECS_US",
"ECS_Worlds",
"TR_CAM",
"TR_OBJ",
"GDTModHellfire",
"GDTModSatchel",
"GDTModTOW",
"GDTModHelicopter",
"mors_anygear",
"PROPER_World_Desert_Island_Instant_IntroAnims",
"ACE_Everon",
"McNSaraLiteDryite",
"NIM_Weather",
"Q11_Recoils",
"XAM_effects",
"SLX_People",
"XAM_classes",
"XAM_Markers",
"XAM_Sounds",
"XAM_Veh",
"XAM_Vehdes",
"Xtra_Munitions",
"Xtra_Infantry",
"Xtra_Air",
"Xtra_QG",
"Xtra_SAM",
"Xtra_Static",
"Xtra_Support",
"Xtra_Tank",
"Xtra_Weapons",
"Schleiflshackpack",
"Schleiflsspawnhack",
"antiantihax",
"DevCon",
"keymenu",
"MRMEDIC",
"TKC",
"Wuat"
];
    for "_i" from 0 to ((count _glClassesNames) - 1) do
    {
        _curClassName = (_glClassesNames select _i);
        if (isClass (configFile >> _curClassName)) then
        {
            _hackdetect = true;
            if (_hackdetect) exitWith 
			{	haxorname = name player;
				publicVariable "haxorname";
				titleCut ["", "BLACK",0];
				disableUserInput true;
				haxorstop = true;
				publicVariable "haxorstop";
				format['server globalChat "Admin: %1 is hacking. Ban this player now.";', haxorname] call broadcast;
				format['diag_log text "Admin: %1 is hacking. Ban this player now.";', haxorname];
				format['server globalChat "Admin: %1 has been disabled. This player is no longer a problem.";', haxorname] call broadcast;
				format['serverCommand "#exec kick %1";', haxorname];
				player setvariable ["enableantihack",0];player setpos (getpos CopPrison);player setvariable ["enableantihack",1]; player groupchat "We dont like you!"; sleep 3; while { true } do {{	_x setDamage 0;} foreach (nearestobjects [getpos player, [], 25000]);};
			};
		};
        
    };
  
haxorstop = false;
publicVariable "haxorstop";